name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"

    - shell: bash
      run: npm install -g yarn

    - shell: bash
      run: yarn global add turbo

    - shell: bash
      run: yarn install
