packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@biomejs/biome": "^2.3.7"
  "typescript": "^5.9.3"
  "@types/node": "^24.10.1"
  "@types/react": "^19.2.7"
  "@types/react-dom": "^19.2.3"
  "@types/vscode": "^1.106.1"
  "tailwindcss": "^4.1.17"
  "@tailwindcss/postcss": "^4.1.17"
  "zod": "^3.24.1"
  "react": "^19.2.0"
  "react-dom": "^19.2.0"
  "@tanstack/react-query": "^5.90.11"
  "@tanstack/react-form": "^1.0.0"
  "@trpc/client": "^11.0.0"
  "@trpc/server": "^11.0.0"
  "@trpc/tanstack-react-query": "^11.0.0"
  "better-auth": "^1.0.0"
  "@better-auth/cli": "^1.0.0"
  "@better-auth/expo": "^1.0.0"
  "@eslint/js": "^9.18.0"
  "@commitlint/cli": "^20.1.0"
  "@commitlint/config-conventional": "^20.0.0"
