// AUTO-GENERATED - DO NOT EDIT
// Generated by vite.config.ts during webview build
// To update, modify the routers in src/rpc/routers/ and rebuild

import type { RouterRecord, Procedure } from "@clive/webview-rpc";

function createProcedureShape<T extends "query" | "mutation" | "subscription">(
  type: T,
): Procedure<unknown, unknown, unknown, T> {
  return {
    _def: {
      type,
      input: undefined,
      output: undefined,
      context: undefined,
    },
  } as Procedure<unknown, unknown, unknown, T>;
}

export const routerShape: RouterRecord = {
  agents: {
    planTests: createProcedureShape("subscription"),
    cancelTest: createProcedureShape("mutation"),
    previewDiff: createProcedureShape("mutation"),
    approveToolCall: createProcedureShape("mutation"),
    abortToolCall: createProcedureShape("mutation"),
    abortAllToolCalls: createProcedureShape("mutation"),
    acceptEdit: createProcedureShape("mutation"),
    rejectEdit: createProcedureShape("mutation"),
    getPendingEdits: createProcedureShape("query"),
  },
  auth: {
    startDeviceAuth: createProcedureShape("mutation"),
    cancelDeviceAuth: createProcedureShape("mutation"),
    checkSession: createProcedureShape("query"),
    logout: createProcedureShape("mutation"),
    storeToken: createProcedureShape("mutation"),
  },
  config: {
    getApiKeys: createProcedureShape("query"),
    saveApiKey: createProcedureShape("mutation"),
    deleteApiKey: createProcedureShape("mutation"),
    completeOnboarding: createProcedureShape("mutation"),
    getBaseBranch: createProcedureShape("query"),
    setBaseBranch: createProcedureShape("mutation"),
    getTerminalCommandApproval: createProcedureShape("query"),
    setTerminalCommandApproval: createProcedureShape("mutation"),
    getAiProvider: createProcedureShape("query"),
    setAiProvider: createProcedureShape("mutation"),
    getClaudeCliStatus: createProcedureShape("query"),
    authenticateClaudeCli: createProcedureShape("mutation"),
  },
  conversations: {
    start: createProcedureShape("mutation"),
    sendMessage: createProcedureShape("subscription"),
    approveProposal: createProcedureShape("mutation"),
    hasConversation: createProcedureShape("query"),
    hasConversationsBatch: createProcedureShape("query"),
    getHistory: createProcedureShape("query"),
    startBranch: createProcedureShape("mutation"),
    hasBranchConversation: createProcedureShape("query"),
    getBranchHistory: createProcedureShape("query"),
  },
  knowledgeBase: {
    getStatus: createProcedureShape("query"),
    regenerate: createProcedureShape("mutation"),
    regenerateWithProgress: createProcedureShape("subscription"),
    getCategories: createProcedureShape("query"),
  },
  status: {
    branchChanges: createProcedureShape("query"),
    uncommittedChanges: createProcedureShape("query"),
    currentCommit: createProcedureShape("query"),
  },
  system: {
    ready: createProcedureShape("query"),
    log: createProcedureShape("mutation"),
    getTheme: createProcedureShape("query"),
    writePlanFile: createProcedureShape("mutation"),
    openFile: createProcedureShape("mutation"),
  },
};
